"""empty message

Revision ID: fb3a3c6ddd88
Revises: 16f7449e7c13
Create Date: 2020-05-22 10:36:05.152804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3a3c6ddd88'
down_revision = '16f7449e7c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poms', sa.Column('active', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('angSum', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('angry', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('annoyed', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('anxious', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('ashamed', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('bewildered', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('bitter', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('bushed', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('competent', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('conSum', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('confident', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('confused', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('depSum', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('discouraged', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('embarrassed', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('energetic', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('eraSum', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('exhausted', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('fatSum', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('fatigued', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('forgetful', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('fullOfPep', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('furious', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('grouchy', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('helpless', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('hopeless', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('lively', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('miserable', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('nervous', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('onEdge', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('proud', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('resentful', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('restless', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('sad', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('satisfied', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('tenSum', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('tmdSum', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('unableToConcentrate', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('uncertainAboutThings', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('uneasy', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('unhappy', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('vigSum', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('vigorous', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('weary', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('wornOut', sa.Integer(), nullable=True))
    op.add_column('poms', sa.Column('worthless', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poms', 'worthless')
    op.drop_column('poms', 'wornOut')
    op.drop_column('poms', 'weary')
    op.drop_column('poms', 'vigorous')
    op.drop_column('poms', 'vigSum')
    op.drop_column('poms', 'unhappy')
    op.drop_column('poms', 'uneasy')
    op.drop_column('poms', 'uncertainAboutThings')
    op.drop_column('poms', 'unableToConcentrate')
    op.drop_column('poms', 'tmdSum')
    op.drop_column('poms', 'tenSum')
    op.drop_column('poms', 'satisfied')
    op.drop_column('poms', 'sad')
    op.drop_column('poms', 'restless')
    op.drop_column('poms', 'resentful')
    op.drop_column('poms', 'proud')
    op.drop_column('poms', 'onEdge')
    op.drop_column('poms', 'nervous')
    op.drop_column('poms', 'miserable')
    op.drop_column('poms', 'lively')
    op.drop_column('poms', 'hopeless')
    op.drop_column('poms', 'helpless')
    op.drop_column('poms', 'grouchy')
    op.drop_column('poms', 'furious')
    op.drop_column('poms', 'fullOfPep')
    op.drop_column('poms', 'forgetful')
    op.drop_column('poms', 'fatigued')
    op.drop_column('poms', 'fatSum')
    op.drop_column('poms', 'exhausted')
    op.drop_column('poms', 'eraSum')
    op.drop_column('poms', 'energetic')
    op.drop_column('poms', 'embarrassed')
    op.drop_column('poms', 'discouraged')
    op.drop_column('poms', 'depSum')
    op.drop_column('poms', 'confused')
    op.drop_column('poms', 'confident')
    op.drop_column('poms', 'conSum')
    op.drop_column('poms', 'competent')
    op.drop_column('poms', 'bushed')
    op.drop_column('poms', 'bitter')
    op.drop_column('poms', 'bewildered')
    op.drop_column('poms', 'ashamed')
    op.drop_column('poms', 'anxious')
    op.drop_column('poms', 'annoyed')
    op.drop_column('poms', 'angry')
    op.drop_column('poms', 'angSum')
    op.drop_column('poms', 'active')
    # ### end Alembic commands ###
